apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: env-pod
  name: env-pod
  namespace: vmug-cka
spec:
  containers:
  - args:
    - sleep
    - 1h
    env:
    - name: SERVER
      value: vcsa.home.local
    - name: USER
      value: admin@vsphere.local
    - name: PASS
      value: N0N5ecur3
    image: busybox
    name: env-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
