apiVersion: apps/v1
kind: Deployment
metadata:
  name: configured-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
       labels:
         app: nginx
    spec:
      containers:
      - image: nginx:1.19.0
        name: app
        envFrom:
        - configMapRef:
            name: backend-config
