apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod
  name: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 100m

